**01. import numpy package under the name np**

In [1]:
import numpy as np

**02.Print the numpy version and the configuration**

In [2]:
np.__version__

'1.21.0'

**03. Create a null vector of size 10**

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**04. How to find the memory size of any array**

In [4]:
a = np.zeros(100)
num_items = a.size
size_items = a.itemsize
print(f'num_items : {num_items}')
print(f'size_items : {size_items}')
print(f'memory_size : {num_items * size_items}')

num_items : 100
size_items : 8
memory_size : 800


**05. How to get the documentation of the numpy add function from the command line?**

In [5]:
np.info('add')

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

**06. Create a null vector of size 10 but the fifth value which is 1**

In [6]:
# my solution
a = [1.0 if i == 4 else 0.0 for i in range(10)]
a = np.array(a)
print(a)
# solution
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**07. Create a vector with value ranging from 10 to 49**

In [7]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**08. Reverse a vector (first element becomes last)**

In [8]:
a = np.arange(0, 10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**09. Create a 3x3 matrix with values ranging from 0 to 8**

In [9]:
a = np.arange(0, 9)
a = a.reshape(3, -1)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**10. Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]**

In [10]:
a = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(a) # awesome

(array([0, 1, 4]),)