In [1]:
import numpy as np

**11. Create a 3x3 identity matrix**

In [2]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**12. Create a 3x3x3 marray with random values**

In [3]:
a = np.random.rand(3, 3, 3)
a

array([[[0.02571122, 0.46360895, 0.01516786],
        [0.53682388, 0.43733759, 0.26646065],
        [0.53369816, 0.13297916, 0.26736495]],

       [[0.80098917, 0.54256621, 0.70453408],
        [0.44868314, 0.41217662, 0.91169197],
        [0.15444328, 0.93293728, 0.42223692]],

       [[0.02168339, 0.08950227, 0.68668666],
        [0.11584576, 0.84057744, 0.79697318],
        [0.69573145, 0.12360324, 0.47822939]]])

**13. Create a 10x10 array with random values and the minimun and maximum values**

In [4]:
a = np.random.rand(10, 10)
max_ = np.max(a)
min_ = np.min(a)
print(max_, min_)
a

0.9996805212200861 0.000854861256604722


array([[5.97675478e-02, 7.45091413e-01, 5.92583825e-01, 2.27910643e-01,
        1.70055217e-01, 8.54861257e-04, 5.30175290e-01, 4.85350130e-01,
        3.21096804e-01, 7.87677932e-01],
       [8.25019395e-01, 9.99680521e-01, 1.44990247e-01, 3.29949724e-01,
        4.47902070e-01, 9.49597561e-01, 9.42434042e-01, 8.98169316e-01,
        8.69085103e-01, 7.24541790e-01],
       [6.85659477e-01, 8.01166964e-01, 7.08921406e-01, 7.11774906e-02,
        4.98084132e-01, 7.82500577e-01, 4.80382917e-01, 1.95007356e-01,
        2.22983069e-01, 3.80973317e-01],
       [4.04131338e-01, 3.61276114e-02, 1.47489541e-02, 8.04400059e-01,
        3.32202070e-01, 8.27770605e-02, 7.47520366e-01, 1.92595026e-01,
        6.55529269e-01, 9.90990323e-01],
       [6.86534346e-01, 1.95431785e-01, 1.66977874e-01, 3.98129065e-01,
        1.56998327e-01, 7.34323526e-01, 9.88089902e-01, 6.03100221e-01,
        1.76506922e-02, 9.41845161e-01],
       [8.80081614e-01, 7.21377191e-01, 9.10645643e-01, 1.86331458e-01,
   

**14. Create a random vector of size 30 and find the mean value**

In [5]:
a = np.random.rand(30)
print(np.mean(a))
a

0.4666505351630892


array([0.01297183, 0.10688939, 0.61254934, 0.86007663, 0.66518717,
       0.65012987, 0.95476232, 0.16779741, 0.7302735 , 0.45000873,
       0.64156171, 0.33694093, 0.33215836, 0.42629553, 0.77123953,
       0.00464013, 0.68518278, 0.82366825, 0.00192431, 0.26783476,
       0.32966674, 0.93977724, 0.25935245, 0.35767448, 0.63709752,
       0.39820948, 0.014987  , 0.36227581, 0.21352188, 0.98486096])

**15. Create a 2d arrray with 1 on the border and 0 insde**

In [6]:
# my solution
a = np.zeros((4, 4))
print(a)
a = np.pad(a, ((1, 1), (1, 1)), 'constant', constant_values=1)
print(a)

# solution
a = np.ones((6, 6))
a[1:-1, 1:-1] = 0
a

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

**16. How to add a border around an existing array?**

In [7]:
# my solution
a = np.zeros((4, 4))
print(a)
a = np.pad(a, ((1, 1), (1, 1)), 'constant', constant_values=1)
print(a)

# fancy solution
Z = np.ones((6, 6))
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


**17. What is the result of the following expression?**
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```
my answers
1. np.nan
2. False
3. False
4. error? -> nan
5. False -> True
6. False

In [8]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


**18. Create a 5x5 matrix with values 1,2,3,4 just velow the diagonal**

In [9]:
a = np.diag(1 + np.arange(4), k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

**Explore np.diag**

[np.diag document](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)

numpy.diag(v, k=0)

Parameters

v : array_like
if v is a 2-D array, return a copy of its k-th diagonal. if v is a 1-D array, return a 2-D array with v on the k-th diagonal.

k : int, optional
Diagonal in question. The default is 0. Use k > 0 for diagonals above the main diagonal, and k < 0 for diagonals below the main diagonal.

In [10]:
a = np.arange(6)
print(a)
a = 1 + a
print(a)

[0 1 2 3 4 5]
[1 2 3 4 5 6]


In [11]:
a = np.diag(1 + np.arange(6), k = 3)
a
# 아하, k를 늘리면 이 성분들을 main diagonal 의 k 번째 위에, 혹은 아래에 올릴 수 있게끔 array shape을 맞추어주는구나.

array([[0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 6],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

**19. Create a 8x8 matrix and fill it with a checkerboard pattern**

In [12]:
a = np.zeros((8, 8), dtype=int)
a[1::2, 0::2] = 1 # y축으로 1행부터 시작해서 두 칸에 한 번씩 1로 채운다. 단, x축으로는 0번째 열부터 두 열에 한 번씩
a[0::2, 1::2] = 1 # y축으로 0행부터 시작해서 두 칸에 한 번씩 1로 채운다. 단, x축으로는 1번째 열부터 두 열에 한 번씩
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**20. Consider a (6, 7, 8) shape array, what is the index (x, y, z) of the 100th element?**

In [13]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

**Explore np.unravel_index**

[np.unravel_index document](https://numpy.org/doc/stable/reference/generated/numpy.unravel_index.html)

np.unravel_index(indices, shape, order='C')

Parameters

indices: array_like
An integer array whose elements are indices into the flattened version of an array of dimensions shape.


shape: tuple of ints
The shape of the array to use for unraveling indices.


order : {'C', 'F'}, optional, default='C'
Determines whether the indices should be viewed as indexing in row-major (C-style) or column-major (Fortran-style) order.


In [14]:
np.unravel_index(10, (3, 7)) 
# 아하, shape 인자의 shape을 가지는 array를 flatten시켰을 때 
# indices에 있는 친구들이 기존 array에서 어떤 위치에 있는지를 보는 거구나.

(1, 3)

In [15]:
np.unravel_index([99, 100], (6, 7, 8))
# indices에 여러 개의 인자를 넣어주면 각 축의 좌표들을 반환해주는구나.

(array([1, 1]), array([5, 5]), array([3, 4]))

In [16]:
np.unravel_index(99, (6, 7, 8), order='F')
# order를 column-major로 바꾸어주었더니 반환되는 인덱스가 달라지는 것을 확인할 수 있다.

(3, 2, 2)