In [1]:
import numpy as np

**21. Create a checkerboard 8x8 matrix using the tile function**

**Explore np.tile**

In [2]:
np.info('tile')

     *** Found in numpy ***
 tile(A, reps)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Rep

In [3]:
a = np.array([[1, 0], [0, 1]])
np.tile(a, (4, 4)) # awesome

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**22. Normalize a 5x5 random matrix**

In [4]:
a = np.random.rand(5, 5)
norm = np.mean(a)
std = np.std(a)
b = (a  - norm) / std
b

array([[-1.06664799,  0.66274824,  0.73376853,  0.45411645,  0.38330577],
       [-0.5000585 , -0.44701974, -1.40637562,  1.4817366 ,  1.32029938],
       [-1.42176897,  0.71446734, -0.12994647,  0.7600459 , -0.56691445],
       [ 1.07202393,  1.37846098, -1.50366888,  0.0282999 , -0.66313194],
       [-1.69454036,  1.52947184, -1.05483679, -0.59790855,  0.53407337]])

**23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)**

In [5]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

**24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)**

In [6]:
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)
a@b

array([[0.3047514 , 0.66470621],
       [0.33125251, 0.71317578],
       [0.53102109, 1.19473105],
       [0.50655334, 1.11133575],
       [0.38128635, 0.89329339]])

In [7]:
np.matmul(a, b)

array([[0.3047514 , 0.66470621],
       [0.33125251, 0.71317578],
       [0.53102109, 1.19473105],
       [0.50655334, 1.11133575],
       [0.38128635, 0.89329339]])

**25. Given a 1D array, negate all elements which are between 3 and 8, in place.**

In [8]:
a = np.arange(11)
mask = (3 < a) & (a < 8)
mask
a[mask] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

**26. What is the output of the following script?**
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

- answer


In [9]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1)) # ?

9
10


**27. What are the result of the following expressions?**

**28. What are the result of the following expressions?**
```python
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))
```

In [10]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-10-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-10-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


**29. How to round away from zero a float array ?**

In [11]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))
# 0보다 크면 올림, 작으면 내림.

[-5.99734733 -6.33925253  6.3920537   4.3773532   6.29985978 -5.5348404
 -6.88693061  1.0596027  -4.55241316 -9.32123542]
[ -6.  -7.   7.   5.   7.  -6.  -7.   2.  -5. -10.]
[ -6.  -7.   7.   5.   7.  -6.  -7.   2.  -5. -10.]


In [12]:
np.info(np.where)
# np.where 에 3항 조건문 같은 기능이 있다는 것은 처음 알았다.


 where()

where(condition, [x, y])

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples
--

**30. How to find common values between two arrays?**

In [13]:
a = np.arange(1, 10)
b = np.arange(5, 20)
print(np.intersect1d(a, b, return_indices=True))
# return_indices 옵션을 주면 (intersect_values, indices of values at a, indices of values at b) 순으로 반환된다.

(array([5, 6, 7, 8, 9]), array([4, 5, 6, 7, 8]), array([0, 1, 2, 3, 4]))


In [14]:
np.info('intersect1d')

     *** Found in numpy ***
 intersect1d(ar1, ar2, assume_unique=False, return_indices=False)

Find the intersection of two arrays.

Return the sorted, unique values that are in both of the input arrays.

Parameters
----------
ar1, ar2 : array_like
    Input arrays. Will be flattened if not already 1D.
assume_unique : bool
    If True, the input arrays are both assumed to be unique, which
    can speed up the calculation.  If True but ``ar1`` or ``ar2`` are not
    unique, incorrect results and out-of-bounds indices could result.
    Default is False.
return_indices : bool
    If True, the indices which correspond to the intersection of the two
    arrays are returned. The first instance of a value is used if there are
    multiple. Default is False.

    .. versionadded:: 1.15.0

Returns
-------
intersect1d : ndarray
    Sorted 1D array of common and unique elements.
comm1 : ndarray
    The indices of the first occurrences of the common values in `ar1`.
    Only provided if `return_in