In [1]:
import numpy as np

### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [3]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[(([0.], 0.), (0., 0., 0.)) (([0.], 0.), (0., 0., 0.))
 (([0.], 0.), (0., 0., 0.)) (([0.], 0.), (0., 0., 0.))
 (([0.], 0.), (0., 0., 0.)) (([0.], 0.), (0., 0., 0.))
 (([0.], 0.), (0., 0., 0.)) (([0.], 0.), (0., 0., 0.))
 (([0.], 0.), (0., 0., 0.)) (([0.], 0.), (0., 0., 0.))]


/var/folders/gz/t8526n4x0v3g9cdsyk8jmz9c0000gn/T/ipykernel_15226/2508704418.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, (1,)),


In [4]:
Z['position']

array([([0.], 0.), ([0.], 0.), ([0.], 0.), ([0.], 0.), ([0.], 0.),
       ([0.], 0.), ([0.], 0.), ([0.], 0.), ([0.], 0.), ([0.], 0.)],
      dtype=[('x', '<f8', (1,)), ('y', '<f8')])

In [6]:
Z['position']['x']

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [5]:
Z['color']

array([(0., 0., 0.), (0., 0., 0.), (0., 0., 0.), (0., 0., 0.),
       (0., 0., 0.), (0., 0., 0.), (0., 0., 0.), (0., 0., 0.),
       (0., 0., 0.), (0., 0., 0.)],
      dtype=[('r', '<f8'), ('g', '<f8'), ('b', '<f8')])

In [7]:
Z['color']['r']

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)


In [23]:
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         1.094751   0.78060604 ... 0.88850599 0.78085119 0.6912468 ]
 [1.094751   0.         0.50628712 ... 0.58515995 0.66734689 0.41616171]
 [0.78060604 0.50628712 0.         ... 0.80253781 0.16782829 0.40884187]
 ...
 [0.88850599 0.58515995 0.80253781 ... 0.         0.95418651 0.39848742]
 [0.78085119 0.66734689 0.16782829 ... 0.95418651 0.         0.55597173]
 [0.6912468  0.41616171 0.40884187 ... 0.39848742 0.55597173 0.        ]]


In [28]:
# Explore np.atleast_2d
a = [1, 2, 3]
b = np.atleast_2d(a)
print(b)

c = [[1, 2, 3]]
d = np.atleast_2d(c)
print(c)

[[1 2 3]]
[[1, 2, 3]]


### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [32]:
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
Y = Z.view(np.int32)
print(Y)
Y[:] = Z
print(Y)
print(Z.astype(np.int32))

[57.50166   11.196404  33.64052   13.2336445 52.44966    2.1205459
 81.34661   45.757217  14.469437  73.918755 ]
[1113981363 1093870713 1107726308 1096006914 1112657012 1074247430
 1117958519 1110902628 1097302736 1116984935]
[57 11 33 13 52  2 81 45 14 73]
[0 0 0 0 0 0 0 0 0 0]


In [33]:
# Explore np.view
# ??

### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [34]:
# Answer
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)
# 결측치 있는 데이터 불러올 때 유용할 듯.

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/var/folders/gz/t8526n4x0v3g9cdsyk8jmz9c0000gn/T/ipykernel_15226/1868410621.py:10: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)


In [35]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])
    
# 알아는 두겠지만 이런 연산은 numpy/tensor의 강점을 하나도 못 살린 것이라 생각함

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [38]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10)) 
# 가운데로 갈 수록 0에 가까워지는 X, Y
# 그런데 sigma를 빼주니까 가운데로 갈 수록 1에 가까워진다.
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

### 57. How to randomly place p elements in a 2D array? (★★☆)

In [46]:
n = 10
p = 3
Z = np.zeros((n,n))
points = np.random.choice(range(n * n), p, replace=False)
print(points)
np.put(Z, points,2)
print(Z)

[56 20 79]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [42]:
# Explore np.put
# numpy.put(a, ind, v, mode='raise')
a = np.array([1, 2, 3])
np.put(a, 2, 4)
a

array([1, 2, 4])

In [45]:
# Explore np.random.choice
# random.choice(a, size=None, replace=True, p=None)
np.random.choice(range(n*n), 3, replace=False)

array([49, 44,  5])

In [43]:
# Explore range
range(5 * 5)

range(0, 25)

In [47]:
# Explore numpy indexing
a = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
np.put(a, 5, 4) # a[5] = 4 하면 에러난다. 짱신기함 np.put은 신이다..
a

array([[1, 1, 1],
       [2, 2, 4],
       [3, 3, 3]])

### 58. Subtract the mean of each row of a matrix (★★☆)


In [53]:
a = np.random.rand(5, 10)
print(a)
means = np.mean(a, axis=1, keepdims=True)
print(means)
print(a - means)

[[0.50986643 0.50888022 0.91147712 0.40806335 0.64297594 0.22767765
  0.33755217 0.7810862  0.60109967 0.54854172]
 [0.64737767 0.05172335 0.31207462 0.6089103  0.31600161 0.85003875
  0.48368465 0.15160959 0.70339548 0.350926  ]
 [0.49028128 0.70931966 0.24695181 0.62428722 0.34049673 0.87200792
  0.04897295 0.99173294 0.57630224 0.14450536]
 [0.46484253 0.24952328 0.32989605 0.86961983 0.06640394 0.04260178
  0.62434605 0.05742843 0.69625975 0.97952936]
 [0.57999322 0.73553384 0.61363484 0.2173608  0.03162975 0.7897097
  0.13535297 0.50761488 0.57962763 0.45986459]]
[[0.54772205]
 [0.4475742 ]
 [0.50448581]
 [0.4380451 ]
 [0.46503222]]
[[-0.03785562 -0.03884183  0.36375507 -0.1396587   0.09525389 -0.3200444
  -0.21016987  0.23336415  0.05337762  0.00081967]
 [ 0.19980346 -0.39585085 -0.13549958  0.1613361  -0.13157259  0.40246455
   0.03611045 -0.29596462  0.25582128 -0.0966482 ]
 [-0.01420453  0.20483385 -0.257534    0.11980141 -0.16398908  0.36752211
  -0.45551286  0.48724713  0.07

### 59. How to sort an array by the nth column? (★★☆)

In [55]:
n = 4
a = np.random.rand(5, 10)
print(a)
sorted(a, key=lambda x: x[4])

[[0.8752103  0.19329825 0.3187763  0.38283759 0.89460155 0.90089853
  0.0303427  0.49807821 0.14482062 0.37390306]
 [0.34547784 0.87594714 0.80564934 0.38216269 0.92190276 0.16295619
  0.85772522 0.74457912 0.52162726 0.26086726]
 [0.93554915 0.86581287 0.72976286 0.88715554 0.46914163 0.2167584
  0.51759474 0.24180407 0.22435488 0.86523069]
 [0.95776701 0.15387996 0.31332427 0.80148625 0.67368921 0.01462879
  0.96083822 0.63024667 0.09796474 0.13026592]
 [0.21331909 0.80740159 0.85101457 0.85714398 0.6788417  0.32848741
  0.23719958 0.14466198 0.29344947 0.1550756 ]]


[array([0.93554915, 0.86581287, 0.72976286, 0.88715554, 0.46914163,
        0.2167584 , 0.51759474, 0.24180407, 0.22435488, 0.86523069]),
 array([0.95776701, 0.15387996, 0.31332427, 0.80148625, 0.67368921,
        0.01462879, 0.96083822, 0.63024667, 0.09796474, 0.13026592]),
 array([0.21331909, 0.80740159, 0.85101457, 0.85714398, 0.6788417 ,
        0.32848741, 0.23719958, 0.14466198, 0.29344947, 0.1550756 ]),
 array([0.8752103 , 0.19329825, 0.3187763 , 0.38283759, 0.89460155,
        0.90089853, 0.0303427 , 0.49807821, 0.14482062, 0.37390306]),
 array([0.34547784, 0.87594714, 0.80564934, 0.38216269, 0.92190276,
        0.16295619, 0.85772522, 0.74457912, 0.52162726, 0.26086726])]

### 60. How to tell if a given 2D array has null columns? (★★☆)


In [58]:
# Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[0 1 0 0 2 0 2 1 0 1]
 [2 2 0 0 1 0 1 0 1 2]
 [1 1 0 2 1 1 1 2 0 0]]
True


In [59]:
# Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[2 1 1 2 2 2 1 0 2 1]
 [1 2 0 1 1 1 2 2 2 2]
 [1 0 2 2 0 2 0 2 0 0]]
False
